---
- name: Disable IPv6 on grub
  replace:
    dest: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*ipv6.disable)\"[^\"]*)(\".*)'
    replace: '\1 ipv6.disable=1\2'
  notify:
    - grub restart