---
- name: 3.1.1 Disable IPv6
  replace:
    dest: /etc/default/grub
    regexp: '^(GRUB_CMDLINE_LINUX=(?!.*ipv6.disable)\"[^\"]*)(\".*)'
    replace: '\1 ipv6.disable=1\2'
  notify:
    - grub restart